# Generated by Django 2.0.5 on 2018-05-12 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='chians_address',
            field=models.CharField(default=True, max_length=300),
        ),
    ]
