# Generated by Django 2.0.5 on 2018-05-12 01:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_names', models.CharField(max_length=1000)),
                ('label_name', models.CharField(max_length=100)),
                ('label_values', models.CharField(max_length=300)),
                ('task_type', models.CharField(choices=[('classification', 'classification'), ('regression', 'regression')], max_length=100)),
                ('upload_file', models.FileField(upload_to='')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
