# Generated by Django 2.0.5 on 2018-05-12 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('featureselection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskResult',
            fields=[
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='featureselection.Task')),
                ('original_accuracy', models.CharField(max_length=1000)),
                ('cfs_result', models.CharField(max_length=1000)),
                ('cfs_accuracy', models.FloatField()),
                ('alphainvesting_result', models.CharField(max_length=1000)),
                ('alphainvesting_accuracy', models.FloatField()),
                ('chi_result', models.CharField(max_length=1000)),
                ('chi_file', models.CharField(max_length=1000)),
            ],
        ),
    ]
