# Generated by Django 2.0.5 on 2018-05-12 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('featureselection', '0002_taskresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskresult',
            name='alphainvesting_time',
            field=models.FloatField(default=True),
        ),
        migrations.AddField(
            model_name='taskresult',
            name='cfs_time',
            field=models.FloatField(default=True),
        ),
    ]
