# Generated by Django 2.0.5 on 2018-05-12 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('featureselection', '0003_auto_20180512_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskresult',
            name='chi_time',
            field=models.FloatField(default=True),
        ),
    ]
