# Generated by Django 2.0.5 on 2018-05-15 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('featureselection', '0007_auto_20180512_1948'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_result', models.CharField(max_length=100)),
                ('accuracy', models.FloatField()),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='featureselection.Task')),
            ],
        ),
    ]
