# Generated by Django 2.0.5 on 2018-06-17 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('featureselection', '0011_taskresult_best_result_system'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CFS_num', models.IntegerField(default=0)),
                ('Alpha_num', models.IntegerField(default=0)),
                ('Chi2_num', models.IntegerField(default=0)),
                ('ReliefF_num', models.IntegerField(default=0)),
                ('User_num', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='taskresult',
            name='choosed_result',
            field=models.CharField(default=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='taskresult',
            name='choosed_result_from',
            field=models.CharField(default=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='taskresult',
            name='ischoosed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='taskresult',
            name='system_result_from',
            field=models.CharField(default=True, max_length=1000),
        ),
    ]
